
sinonimos_func = {
    "empezar": ["empezo", "comenzo", "inicio", "iniciar", "principio", "arranco"],
    "crear": ["creo", "creada", "surgio", "fundar", "originar", "establecer"],
    "originar": ["origino", "surgio", "empezo", "nacio", "aparecio"],
    "oficial": ["oficial", "reconocida", "legal", "permitida", "valida"],
    "significar": ["significa", "que es", "que significa", "definir", "es"],
    "aprender": ["aprendian", "enseñar", "enseña", "estudiar", "capacitarse", "educar"],
    "igual": ["igual", "parece", "similar", "semejante"],
    "tener": ["tiene", "posee", "contar con", "poseer", "tener"],
    "escuela": ["escuela", "instituto", "colegio", "universidad", "centro"],
    "lengua": ["lengua", "lenguaje", "idioma", "dialecto"],
    "usar": ["usan", "utilizan", "emplean", "usan"],
    "prohibir": ["prohibida", "impedir", "vetar", "excluir"],
    "preservar": ["preserva", "conservar", "mantener", "cuidar"],
    "gramatica": ["gramatica", "estructura", "reglas", "normas"],
    "ley": ["ley", "norma", "reglamento", "legislacion"],
    "defender": ["defienden", "proteger", "apoyar", "luchar por"],
    "cambiar": ["cambia", "evoluciona", "modifica", "transforma"],
    "dialecto": ["dialectos", "variantes", "versiones", "version"],
    "alfabeto": ["alfabeto", "abecedario", "manual"],
    "importante": ["importante", "clave", "esencial", "fundamental"],
    "ensenar": ["ensena", "impartir", "dar clase", "educar"],
    "universidad": ["universidades", "instituciones", "colegios"],
    "comunicacion": ["comunicacion", "mensaje", "transmision", "intercambio"],
    "celebrar": ["celebra", "conmemorar", "festejar", "recordar"],
    "dificil": ["dificil", "complicado", "complejo", "duro"],
    "nino": ["ninos", "menores", "peques", "criaturas"],
    "diccionario": ["diccionarios", "glosarios", "vocabularios"],
    "constitucion": ["constitucion", "ley fundamental", "carta magna"],
    "usuario": ["usuarios", "personas", "gente", "comunidad"],
    "solo": ["solo", "solamente", "únicamente", "exclusivamente"],
    "interprete": ["interpretes", "traductores", "mediadores"],
    "traducir": ["traducir", "interpretar", "convertir", "transcribir"],
    "explicar": ["explicar", "aclarar", "detallar", "describir", "ilustrar"],
    "pregunta": ["pregunta", "consulta", "interrogante", "cuestionamiento"],
    "respuesta": ["respuesta", "solucion", "contestacion", "replica"],  
    "ser": ["ser", "existir", "constar", "pertenecer", "estar"],
    "funcionar": ["funcionar", "operar", "trabajar", "marchar", "andar"],
    "usar": ["usar", "utilizar", "emplear", "aplicar", "manejar"],
    "tener": ["tener", "contar con", "poseer", "disponer de"],
    "poder": ["poder", "ser capaz de", "lograr", "permitir"],
    "significar": ["significar", "querer decir", "representar", "denotar"],
    "reconocer": ["reconocer", "identificar", "validar", "aceptar", "certificar"],
    "comenzar": ["comenzar", "empezar", "iniciar", "arrancar", "principiar"],
    "crear": ["crear", "hacer", "fabricar", "producir", "desarrollar", "construir"],
    "originar": ["originar", "surgir", "nacer", "proceder", "generar", "aparecer"],
    "enseñar": ["enseñar", "instruir", "mostrar", "impartir", "explicar", "dictar", "aprender"],
    "preservar": ["preservar", "conservar", "mantener", "cuidar", "proteger", "salvaguardar"],
    "defender": ["defender", "proteger", "resguardar", "amparar", "apoyar", "sostener"],
    "cambiar": ["cambiar", "modificar", "transformar", "alterar", "variar", "evolucionar"],
    "celebrar": ["celebrar", "conmemorar", "festejar", "recordar", "honrar"],
    "mostrar": ["mostrar", "exhibir", "presentar", "demostrar", "exponer"],
    "estudiar": ["estudiar", "aprender", "investigar", "analizar", "explorar"],
    "prohibir": ["prohibir", "impedir", "vetar", "bloquear", "excluir"],
    "existir": ["existir", "haber", "presentar", "contar con", "estar"],
    "definir": ["definir", "explicar", "determinar", "establecer", "señalar"],
    "guardar": ["guardar", "almacenar", "conservar", "salvar", "archivar"],
    "actualizar": ["actualizar", "renovar", "modernizar", "mejorar", "poner al día"],
    "conectar": ["conectar", "enlazar", "unir", "vincular", "relacionar"],
    "apagar": ["apagar", "desconectar", "cerrar", "detener", "desactivar"],
    "saber": ["saber", "conocer", "entender", "comprender", "informarse"],
    "compartir": ["compartir", "dividir", "repartir", "distribuir", "socializar"],
    "reconocer": ["reconocer", "identificar", "aceptar", "validar", "certificar"],
    "limpiar": ["limpiar", "asear", "desinfectar", "fregar", "lavar"],
    "pesar": ["pesar", "tener peso", "medir peso", "balanza"],
    "servir": ["servir", "funcionar", "utilizar", "ser útil"],
    "reiniciar": ["reiniciar", "resetear", "reinicializar", "volver a empezar"],
    "traducir": ["traducir", "interpretar", "convertir", "transcribir"],
    "detectar": ["detectar", "identificar", "localizar", "descubrir", "percebir"],
    "conectar": ["conectar", "unir", "enlazar", "vincular", "relacionar"],
    "permitir": ["permitir", "autorizar", "dejar", "habilitar"],
    "mostrar": ["mostrar", "enseñar", "exhibir", "presentar", "demostrar"]

}
